# --------------------------------------------------------------------------
# 스프링 부트 애플리케이션 환경별 프로파일 그룹화
# --------------------------------------------------------------------------
spring:
  profiles:
    active: dev
    group:
      dev: dev, common
      local: local, common



# --------------------------------------------------------------------------
# 환경별 프로파일 설정
# --------------------------------------------------------------------------
--- # 공통 환경
spring:
  config:
    activate:
      on-profile:
        - common
  main:
    banner-mode: OFF
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
      cache:
        period: 36000

mybatis:
  type-aliases-package: org.subin.orbit.domain.**.dto
  type-handlers-package: org.subin.orbit.global.common.mybatis
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mappers/*_mapper.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


--- # 개발 환경
spring:
  config:
    activate:
      on-profile:
        - dev
  # 개발을 위한 H2 인메모리 데이터베이스 연결 정보 설정
  datasource:
    url: jdbc:h2:mem:orbit_test;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
  # 데이터베이스 스키마 버전 관리 : 비활성화
  flyway:
    enabled: false
  sql:
    # 스프링 부트 초기 데이터 설정
    init:
      # ALWAYS : 애플리케이션이 실행될 때마다 SQL스크립트 실행 , EMBEDDED : 내장 데이터베이스 사용시에만 SQL스크립트 실행, NEVER : SQL스크립트 싫행X
      mode: EMBEDDED
      schema-locations:
        - classpath:sql/h2/schema.sql
        - classpath:sql/h2/data.sql
  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  level:
    root: info

server:
  port: 80


