DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	ID					INT						NOT NULL AUTO_INCREMENT,
	EMAIL				VARCHAR(40)				NOT NULL,
	PASSWORD			VARCHAR(255)			NOT NULL,
	NAME				VARCHAR(12)				NOT NULL,
	PHONE				VARCHAR(11)				NOT NULL,
	LOGIN_TYPE			VARCHAR(5)				NOT NULL,
	ENABLED				TINYINT(1)				NOT NULL,
	CREATED_AT			DATETIME				NOT NULL DEFAULT NOW(),
	UPDATED_AT			DATETIME				NOT NULL,
	DELETE_YN			CHAR(1)					NOT NULL DEFAULT 'N',
	DELETED_AT			DATETIME				NOT NULL,
	PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS USER_ROLES;

CREATE TABLE USER_ROLES (
	USER_ID				INT						NOT NULL,
	ROLE				VARCHAR(20)				NOT NULL,
	DELETE_YN			CHAR(1)					NOT NULL DEFAULT 'N',
	DELETED_AT			DATETIME				NOT NULL,
	CREATED_AT			DATETIME				NOT NULL DEFAULT NOW(),
	UPDATED_AT			DATETIME				NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON UPDATE CASCADE ON DELETE CASCADE
);


DROP TABLE IF EXISTS TASKS;

CREATE TABLE TASKS (
    TASK_ID                     INT					NOT NULL AUTO_INCREMENT,
    NAME                        VARCHAR(50) 		NOT NULL,
    SORT                        INT					NOT NULL DEFAULT 0,
    USE_YN                      CHAR(1)				NOT NULL DEFAULT 'Y',
    CREATED_AT                  DATETIME			NOT NULL DEFAULT NOW(),
    UPDATED_AT                  DATETIME			NOT NULL,
    PRIMARY KEY (TASK_ID)
);